#!/bin/zsh
#
# Launch the Alfred Editor from command line.
#

VPREFS="${HOME}/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/"
NVPREFS="${HOME}/Library/Application Support/Alfred 2/Workflow Data/"

###############################################################################
# Read the bundleid from the workflow's info.plist
###############################################################################
getBundleId() {
  /usr/libexec/PlistBuddy  -c "Print :bundleid" "info.plist"
}

###############################################################################
# Get the workflow data dir
###############################################################################
getDataDir() {
  local BUNDLEID=$(getBundleId)
  echo "${NVPREFS}${BUNDLEID}"
}

###############################################################################
# Get the workflow cache dri
###############################################################################
getCacheDir() {
  local BUNDLEID=$(getBundleId)
  echo "${VPREFS}${BUNDLEID}"
}

/usr/bin/osascript -e "tell application \"Alfred 2\" to run trigger \"EditAlfredEditor\" in workflow \"com.customct.AlfredEditor\" with argument \"$(pwd)/$1\"";
